import { Class, ResolvedGuard, ResolvedGuardPerMod, ResolvedProvider } from '@ditsmod/core';

import type { RequestContext } from '#services/request-context.js';
import type { TrpcRouteExtension } from '#extensions/trpc-route.extension.js';

/**
 * This metadata is generated by {@link TrpcRouteExtension}, and available via DI.
 */
export class RouteMeta {
  /**
   * A resolved provider that is assigned to call a method of a controller that is bound to a specific route.
   */
  resolvedHandler?: ResolvedProvider;
  /**
   * An array of DI tokens used to look up `CanActivate()` handlers,
   * in order to determine if the current user is allowed to activate the controller.
   * By default, any user can activate.
   */
  resolvedGuards?: ResolvedGuard[];
  resolvedGuardsPerMod?: ResolvedGuardPerMod[];
  Controller: Class;
  methodName: string | symbol;
  routeHandler?: (ctx: RequestContext) => Promise<any>;
}
