approvedGitRepositories:
  - '**'

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 1440

npmScopes:
  ts-stack:
    npmMinimalAgeGate: 0

npmPreapprovedPackages:
  - 'typescript'
  - '@typescript/*'
