import { edk } from '@ditsmod/core';
import { ParameterObject, ReferenceObject, XPathItemObject } from '@ts-stack/openapi-spec';

/**
 * This metadata is generated by `ROUTES_EXTENSIONS` group, and available via DI per
 * a route.
 */
export class OasRouteMeta extends edk.RouteMeta {
  pathItem: XPathItemObject;
  /**
   * Merged parameters with `ParameterObject[]` from `PathItemObject` and `OperationObject`.
   */
  params: ParameterObject[];
  /**
   * Merged parameters with `ReferenceObject[]` from `PathItemObject` and `OperationObject`.
   */
  paramsRefs: ReferenceObject[];
}
