export {
  ProhibitSavingModulesSnapshot,
  ProvidersCollision,
  ResolvingCollisionsNotImportedInModule,
  CannotResolveCollisionForMultiProviderPerLevel,
  CannotResolveCollisionForMultiProviderPerApp,
  ExtensionConfigCauseCyclicDeps,
  ResolvingCollisionsNotExistsOnThisLevel,
  ProvidersPerAppMissingTokenName,
  ResolvingCollisionsNotImportedInApplication,
  ModuleShouldHaveValue,
  ForbiddenExportProvidersPerApp,
  ForbiddenExportNormalizedProvider,
  ExportingUnknownSymbol,
  InvalidExtension,
  ReexportFailed,
  UndefinedModule,
  ResolvedCollisionTokensOnly,
  ModuleDoesNotHaveDecorator,
  InvalidModRefId,
  CircularDepsInImports,
  FailedStage3,
  FailedStage2,
  FailedCreateInjectorPerMod,
  FailedCollectingMetadata,
  ModuleNotImportedInApplication,
  LoggerNotSet,
  ExtensionFailed,
  CircularDepsBetweenExtensions,
  NotDeclaredInAfterExtensionList,
  NoProviderDuringResolveImports,
  RootNotHaveDecorator,
  FailAddingToImports,
  FailRemovingImport,
  ForbiddenRollbackEmptyState,
  ModuleIdNotFoundInModuleManager,
  NormalizationFailed,
} from '#error/core-errors.js';

export * from '#di/errors.js';
