export {
  FailImportProviders,
  ProhibitSavingModulesSnapshot,
  ProvidersCollision,
  ResolvingCollisionsNotImportedInModule,
  CannotResolveCollisionForMultiProviderPerLevel,
  CannotResolveCollisionForMultiProviderPerApp,
  ExtensionConfigCauseCyclicDeps,
  ResolvingCollisionsNotExistsOnThisLevel,
  FalseResolvedCollisions,
  ProvidersPerAppMissingTokenName,
  ResolvingCollisionsNotImportedInApplication,
  ModuleShouldHaveValue,
  ForbiddenExportProvidersPerApp,
  ForbiddenExportNormalizedProvider,
  ExportingUnknownSymbol,
  InvalidExtension,
  ReexportFailed,
  UndefinedSymbol,
  ResolvedCollisionTokensOnly,
  ModuleDoesNotHaveDecorator,
  InvalidModRefId,
  CircularDepsInImports,
  FailedStage3,
  FailedStage2,
  FailedCreateInjectorPerMod,
  FailedCollectingMetadata,
  ModuleNotImportedInApplication,
  LoggerNotSet,
  ExtensionFailed,
  CircularDepsBetweenExtensions,
  NotDeclaredInAfterExtensionList,
  NoProviderDuringResolveImports,
  RootNotHaveDecorator,
  FailAddingToImports,
  FailRemovingImport,
  ForbiddenRollbackEmptyState,
  ModuleIdNotFoundInModuleManager,
  NormalizationFailed,
  FailedOverrideMetaAfterStage1,
  CannotReinitInjectorAfterStage1,
  ClassForUseFactoriesWithoutDecorators,
} from '#error/core-errors.js';

export * from '#di/errors.js';
export { CustomError } from '#error/custom-error.js';
export { isChainError, isCustomError } from '#utils/type-guards.js';
export { ErrorInfo } from '#error/error-info.js';
