export {
  FailImportProviders,
  ProhibitSavingModulesSnapshot,
  ProvidersCollision,
  ResolvingCollisionNotImportedInModule,
  CannotResolveCollisionForMultiProviderPerLevel,
  CannotResolveCollisionForMultiProviderPerApp,
  ExtensionConfigCauseCyclicDeps,
  ResolvingCollisionNotExistsOnThisLevel,
  InvalidCollisionResolution,
  AppProviderMissingTokenName,
  ResolvingCollisionNotImportedInApplication,
  ModuleShouldHaveValue,
  ForbiddenExportProvidersPerApp,
  ForbiddenExportNormalizedProvider,
  ExportingUnknownSymbol,
  InvalidExtension,
  ReexportFailed,
  UndefinedSymbol,
  ResolvedCollisionTokensOnly,
  ModuleDoesNotHaveDecorator,
  InvalidModRefId,
  CircularDepsInImports,
  Stage3Failed,
  Stage2Failed,
  ModuleInjectorCreationFailed,
  MetadataCollectionFailed,
  ModuleNotImportedInApplication,
  LoggerNotSet,
  ExtensionFailed,
  CircularDepsBetweenExtensions,
  NotDeclaredInAfterExtensionList,
  NoProviderDuringResolveImports,
  RootNotHaveDecorator,
  ImportAdditionFailed,
  ImportRemovalFailed,
  ForbiddenRollbackEmptyState,
  ModuleIdNotFoundInModuleManager,
  NormalizationFailed,
  MetaOverrideAfterStage1Failed,
  InjectorReinitAfterStage1Forbidden,
  ClassForUseFactoriesWithoutDecorators,
} from '#error/core-errors.js';

export * from '#di/errors.js';
export * from '@ts-stack/chain-error';
export { CustomError } from '#error/custom-error.js';
export { isChainError, isCustomError } from '#utils/type-guards.js';
export { ErrorInfo } from '#error/error-info.js';
