import { Class, ResolvedGuard, ResolvedGuardPerMod, ResolvedProvider } from '@ditsmod/core';
import { RequestContext } from './request-context.js';

/**
 * This metadata is generated by `ROUTE_EXTENSIONS` group, and available via DI.
 */
export class RouteMeta {
  /**
   * A resolved provider that is assigned to call a method of a controller that is bound to a specific route.
   */
  resolvedHandler?: ResolvedProvider;
  /**
   * An array of DI tokens used to look up `CanActivate()` handlers,
   * in order to determine if the current user is allowed to activate the controller.
   * By default, any user can activate.
   */
  resolvedGuards?: ResolvedGuard[];
  resolvedGuardsPerMod?: ResolvedGuardPerMod[];
  Controller: Class;
  methodName: string | symbol;
  routeHandler?: (ctx: RequestContext) => Promise<any>;
}
