import {
  AnyObj,
  Class,
  HttpMethod,
  ModuleMetadata,
  ModuleType,
  NormalizedModuleMetadata,
  RouteHandler,
} from '@ditsmod/core';

import { Tree } from './tree.js';
import { ControllerMetadata } from './controller-metadata.js';
import { GuardPerMod1 } from './interceptors/guard.js';

interface ExtendedModuleMetadata extends ModuleMetadata {
  /**
   * List of modules that contain controllers. Providers and extensions from these modules
   * are not imported into the current module. If the current module has a prefix path,
   * that path will be added to each controller route from the appended modules.
   */
  appends?: Array<ModuleType | AppendsWithParams>;
  /**
   * The application controllers.
   */
  controllers?: Class[];
}

/**
 * This metadata is generated by `ROUTE_EXTENSIONS` group, and available for other extensions
 * that need set routes. The target for this metadata is `PRE_ROUTER_EXTENSIONS` group.
 */
export class MetadataPerMod3 {
  meta: NormalizedModuleMetadata;
  aControllerMetadata: ControllerMetadata[];
  guardsPerMod1: GuardPerMod1[];
}

export interface ObjectAny {
  [k: string]: any;
}

/**
 * This metadata is generated by PreRouterExtension as internal type that need only for it.
 */
export interface PreparedRouteMeta {
  moduleName: string;
  httpMethods: HttpMethod[];
  fullPath: string;
  handle: RouteHandler;
  countOfGuards: number;
}

export type Fn = (...args: any[]) => any;

export type MethodTree = { [P in HttpMethod]?: Tree };

export type Args<T> = T extends (...args: infer A) => any ? A : never;

export enum RouteType {
  static = 0,
  root = 1,
  param = 2,
  catchAll = 3,
}

export class TreeConfig {
  path?: string = '';
  wildChild?: boolean = false;
  type?: number = RouteType.static;
  indices?: string = '';
  children?: any[] = [];
  handle?: Fn | null = null;
  priority?: number = 0;
}

export interface RouteParam {
  key: string;
  value: string;
}

/**
 * Used for module metadata, for `appends` array.
 */
export type AppendsWithParams<T extends AnyObj = AnyObj> = AppendsWithParams1<T> | AppendsWithParams2<T>;

export interface BaseAppendsWithParams<T extends AnyObj = AnyObj> {
  /**
   * The module ID.
   */
  id?: string;
  module: ModuleType<T>;
  // guards?: GuardItem[];
}

export interface AppendsWithParams1<T extends AnyObj = AnyObj> extends BaseAppendsWithParams<T> {
  path: string;
  absolutePath?: never;
}

export interface AppendsWithParams2<T extends AnyObj = AnyObj> extends BaseAppendsWithParams<T> {
  absolutePath: string;
  path?: never;
}
