import { GuardPerMod1, HttpMethod, NormalizedModuleMetadata, RouteHandler } from '@ditsmod/core';

import { Tree } from './tree.js';
import { ControllerMetadata } from './controller-metadata.js';

/**
 * This metadata is generated by `ROUTES_EXTENSIONS` group, and available for other extensions
 * that need set routes. The target for this metadata is `PRE_ROUTER_EXTENSIONS` group.
 */
export class MetadataPerMod3 {
  meta: NormalizedModuleMetadata;
  aControllerMetadata: ControllerMetadata[];
  guardsPerMod1: GuardPerMod1[];
}

export interface ObjectAny {
  [k: string]: any;
}

/**
 * This metadata is generated by PreRouterExtension as internal type that need only for it.
 */
export interface PreparedRouteMeta {
  moduleName: string;
  httpMethods: HttpMethod[];
  path: string;
  handle: RouteHandler;
  countOfGuards: number;
}

export type Fn = (...args: any[]) => any;

export type MethodTree = { [P in HttpMethod]?: Tree };

export type Args<T> = T extends (...args: infer A) => any ? A : never;

export enum RouteType {
  static = 0,
  root = 1,
  param = 2,
  catchAll = 3,
}

export class TreeConfig {
  path?: string = '';
  wildChild?: boolean = false;
  type?: number = RouteType.static;
  indices?: string = '';
  children?: any[] = [];
  handle?: Fn | null = null;
  priority?: number = 0;
}

export interface RouteParam {
  key: string;
  value: string;
}
