import type { HttpMethod, NormalizedModuleMeta } from '@ditsmod/core';
import { ModuleInfo, AppInitHooks, Provider } from '@ditsmod/core';

import { RestImportedProvider } from '#init/types.js';
import type { Tree } from '#services/tree.js';
import type { ModuleScopedGuard } from '#interceptors/guard.js';
import type { RouteHandler } from '#services/router.js';
import type { ControllerMeta } from './controller-metadata.js';
import type { RestInitMeta } from '#init/rest-init-meta.js';

export class RestAppProviders extends AppInitHooks {}

/**
 * See also https://en.wikipedia.org/wiki/URL_redirection#HTTP_status_codes_3xx
 */
export type RedirectStatusCodes = 300 | 301 | 302 | 303 | 307 | 308;

/**
 * This metadata is generated by `RestRouteExtension` group, and available for other extensions
 * that need set routes. The target for this metadata is `DispatcherExtension` group.
 */
export class RouteExtensionMeta {
  normalizedModuleMeta: NormalizedModuleMeta;
  prefixPerMod: string;
  meta: RestInitMeta;
  aControllerMeta: ControllerMeta[];
  guards1: ModuleScopedGuard[];
}

/**
 * This metadata is generated by DispatcherExtension as internal type that need only for it.
 */
export interface PreparedRouteMeta {
  moduleName: string;
  httpMethods: HttpMethod[];
  fullPath: string;
  handle: RouteHandler;
  countOfGuards: number;
}

export type AnyFn = (...args: any[]) => any;

export type MethodTree = { [P in HttpMethod]?: Tree };

export type Args<T> = T extends (...args: infer A) => any ? A : never;

export enum RouteType {
  static = 0,
  root = 1,
  param = 2,
  catchAll = 3,
}

export class RadixTreeNode {
  path?: string = '';
  wildChild?: boolean = false;
  type?: number = RouteType.static;
  indices?: string = '';
  children?: any[] = [];
  handle?: AnyFn | null = null;
  priority?: number = 0;
}

export interface RouteParam {
  key: string;
  value: string;
}
export type Level = 'Req' | 'Rou' | 'Mod';

export class RestModuleInfo extends ModuleInfo {
  path: string;
}
