import type { AnyFn } from './types-and-models.js';

/**
 * Used to store and identify metadata generated by a particular decorator.
 */
export class DecoratorMeta<Value = any> {
  constructor(
    /**
     * The decorator factory function.
     */
    public decorator: AnyFn,
    /**
     * The metadata value produced by the decorator's transformer function,
     * or an array of decorator arguments if no transformer was provided.
     */
    public value: Value,
    /**
     * An identifier for a decorator or a group of decorators whose transformers
     * return metadata of a specific base type. Defaults to the {@link decorator} function if not specified.
     */
    public decoratorId?: AnyFn,
    /**
     * The directory in which the class was declared.
     */
    public declaredInDir?: string,
  ) {
    this.decoratorId ??= decorator;
    if (declaredInDir === undefined) {
      delete this.declaredInDir;
    }
  }
}
