import type { AnyFn } from './types-and-models.js';

/**
 * This class is uses to identifying metadata that is generated by a particular decorator.
 */
export class DecoratorMeta<Value = any> {
  /**
   * @param decorator The decorator factory function.
   */
  constructor(
    public decorator: AnyFn,
    public value: Value,
    public decoratorId?: AnyFn,
    /**
     * The directory in which the class was declared.
     */
    public declaredInDir?: string,
  ) {
    this.decoratorId ??= decorator;
    if (declaredInDir === undefined) {
      delete this.declaredInDir;
    }
  }
}
