name: Publish to npm

on:
  push:
    tags:
      - '*'
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment:
      name: publishing
    strategy:
      matrix:
        package:
          - authjs
          - body-parser
          - cli
          - core
          - cors
          - i18n
          - jwt
          - openapi
          - openapi-validation
          - rest
          - rest-testing
          - session-cookie
          - trpc
        include:
          - package: openapi
            build_ui: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      - name: Enable Corepack
        run: |
          corepack enable
          corepack install
      - name: Install and build
        run: |
          cd packages/${{ matrix.package }}
          yarn install --immutable
          yarn build
      - name: Build OpenAPI UI
        if: matrix.build_ui
        run: |
          cd packages/openapi
          yarn build-ui
      - name: Publish
        run: |
          cd packages/${{ matrix.package }}
          yarn npm publish --provenance --access public --tag next
