export {
  ModuleMustHaveControllers,
  ModuleIncludesInImportsAndAppends,
  InvalidInterceptor,
  CheckingDepsInSandboxFailed,
  HandleAlreadyRegistered,
  OnlyOneWildcardPerPath,
  WildcardRouteConflicts,
  WildcardsMustNonEmpty,
  CatchAllRoutesOnlyAtEnd,
  CatchAllConflictWithExistingHandle,
  NoBeforeCatchAll,
  ConflictsWithExistingWildcard,
  InvalidNodeType,
  GuardNotFound,
  InvalidConfigurationOfRoute,
  FailedValidationOfRoute,
  CreateSecureServerInHttp2NotFound,
  ControllerDoesNotHaveDecorator,
  DuplicateOfControllers,
  InvalidGuard,
} from '#services/rest-errors.js';
